# Generated by Django 5.1.7 on 2025-04-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='endereco_completo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='especializacao',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='professor',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10),
        ),
        migrations.AddField(
            model_name='professor',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='regime_trabalho',
            field=models.CharField(blank=True, choices=[('integral', 'Integral'), ('parcial', 'Parcial'), ('horista', 'Horista')], max_length=50),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
