# Generated by Django 5.1.7 on 2025-04-08 08:09

import professor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_ativo_professor_bairro_professor_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=professor.models.get_unique_filename),
        ),
    ]
