# Generated by Django 5.1.7 on 2025-04-04 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
        ('escola', '0002_instituicao_inicio_teste_instituicao_plano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tipo', models.CharField(choices=[('teorica', 'Aula Teórica'), ('pratica', 'Aula Prática'), ('reuniao', 'Reunião')], default='teorica', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tipo', models.CharField(choices=[('teorica', 'Aula Teórica'), ('pratica', 'Aula Prática'), ('reuniao', 'Reunião')], default='teorica', max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.instituicao')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
