# Generated by Django 5.1.6 on 2025-04-13 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_initial'),
        ('escola', '0003_alter_instituicao_logo'),
        ('sala', '0002_remove_sala_bloco_sala_localizacao_sala_tipo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aula',
            name='data',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('instituicao', 'sala', 'data', 'hora_inicio', 'hora_fim')},
        ),
    ]
