# Generated by Django 5.1.7 on 2025-04-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('destaques', models.TextField(help_text='Separar por vírgulas os recursos')),
                ('mais_popular', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
