# Generated by Django 5.1.7 on 2025-04-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['ordem']},
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='mais_popular',
            new_name='destaque',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='destaques',
        ),
        migrations.AddField(
            model_name='plano',
            name='dias_teste',
            field=models.PositiveIntegerField(default=14, help_text='Duração do teste gratuito em dias'),
        ),
        migrations.AddField(
            model_name='plano',
            name='moeda',
            field=models.CharField(default='EUR', help_text='Ex: EUR, BRL, USD', max_length=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição na página'),
        ),
        migrations.AddField(
            model_name='plano',
            name='personalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='recursos',
            field=models.TextField(default='Até 300 alunos; Gestão básica; Boletins digitais; Suporte via e-mail  ', help_text="Separe cada recurso com ponto e vírgula ';'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='teste_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tipo',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10),
        ),
    ]
