# Generated by Django 5.1.7 on 2025-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='Mamadu Sama', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('pai', 'Pai')], default='admin', max_length=20),
        ),
    ]
