# Generated by Django 5.1.7 on 2025-04-05 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('turma', '0002_alter_turma_options_alter_turma_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='capacidade',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de alunos permitidos na turma', null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='diretor_turma',
            field=models.ForeignKey(blank=True, help_text='Professor responsável como diretor da turma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_diretor', to='professor.professor'),
        ),
    ]
