# Generated by Django 5.1.7 on 2025-04-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_ativo_professor_bairro_professor_cidade_and_more'),
        ('turma', '0003_turma_capacidade_turma_diretor_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas', to='professor.professor'),
        ),
    ]
