# Generated by Django 5.1.7 on 2025-04-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_alter_turma_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professores',
        ),
    ]
