# Generated by Django 5.1.6 on 2025-04-13 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_remove_sala_bloco_sala_localizacao_sala_tipo_and_more'),
        ('turma', '0005_remove_turma_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Indica se a turma está ativa no ano letivo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default='TEMP-0001', help_text='Código interno da turma (ex: 12A-MAT2025)', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre a turma', null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='sala.sala'),
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', help_text='Turno em que a turma funciona', max_length=20),
        ),
        migrations.AddField(
            model_name='turma',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
