# Generated by Django 5.1.6 on 2025-04-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_instituicao_logo'),
        ('turma', '0006_turma_ativa_turma_codigo_turma_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno da turma (ex: 12A-MAT2025)', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'ano_letivo', 'instituicao', 'codigo')},
        ),
    ]
