# Generated by Django 5.1.7 on 2025-04-04 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0002_instituicao_inicio_teste_instituicao_plano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('parentesco', models.CharField(blank=True, max_length=50)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.instituicao')),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo': 'responsavel'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
