# Generated by Django 5.1.7 on 2025-03-27 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='Usuário administrador responsável por esta instituição.', on_delete=django.db.models.deletion.CASCADE, related_name='instituicao_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
