# Generated by Django 5.1.7 on 2025-04-04 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        ('planos', '0002_alter_plano_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='inicio_teste',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planos.plano'),
        ),
    ]
