# Generated by Django 5.1.7 on 2025-04-08 08:09

import escola.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_instituicao_inicio_teste_instituicao_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=escola.models.get_unique_filename),
        ),
    ]
