# Generated by Django 5.1.6 on 2025-04-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='bloco',
        ),
        migrations.AddField(
            model_name='sala',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Sala Normal'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
