# Generated by Django 5.1.7 on 2025-04-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_instituicao_logo'),
        ('matricula', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('numero_matricula', 'instituicao')},
        ),
        migrations.CreateModel(
            name='NumeroAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aluno', models.CharField(max_length=20, unique=True)),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numero_aluno', to='matricula.matricula')),
            ],
        ),
    ]
