# Generated by Django 5.1.7 on 2025-04-09 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_instituicao_logo'),
        ('matricula', '0003_alter_matricula_unique_together_numeroaluno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('numero_matricula', 'instituicao', 'ano_letivo')},
        ),
    ]
