# Generated by Django 5.1.7 on 2025-04-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_alter_matricula_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
