# Generated by Django 5.1.7 on 2025-04-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_remove_aluno_numero_aluno'),
        ('escola', '0003_alter_instituicao_logo'),
        ('matricula', '0005_matricula_cancelada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'instituicao', 'ano_letivo')},
        ),
    ]
