# Generated by Django 5.1.6 on 2025-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_alter_matricula_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroaluno',
            name='numero_aluno',
            field=models.CharField(max_length=20),
        ),
    ]
