# Generated by Django 5.1.6 on 2025-04-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0007_alter_numeroaluno_numero_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='numero_matricula',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
