# Generated by Django 5.1.6 on 2025-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_alter_matricula_numero_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='cancelada',
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15),
        ),
    ]
