# Generated by Django 5.1.6 on 2025-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0009_remove_matricula_ativo_remove_matricula_cancelada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
