# Generated by Django 5.1.7 on 2025-04-09 01:08

import django.db.models.deletion
import financeiro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0005_remove_aluno_numero_aluno'),
        ('escola', '0003_alter_instituicao_logo'),
        ('matricula', '0003_alter_matricula_unique_together_numeroaluno'),
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Recibo de Matrícula', max_length=100)),
                ('tipo', models.CharField(choices=[('matricula', 'Matrícula'), ('mensalidade', 'Mensalidade'), ('exame', 'Exame'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_pdf', models.FileField(upload_to=financeiro.models.get_unique_filename)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_para_responsavel', models.BooleanField(default=False)),
                ('enviado_para_aluno', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='aluno.aluno')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='escola.instituicao')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='matricula.matricula')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matricula', 'Matrícula'), ('mensalidade', 'Mensalidade'), ('exame', 'Exame'), ('outro', 'Outro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='escola.instituicao')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='nivel.nivel')),
            ],
            options={
                'unique_together': {('instituicao', 'nivel', 'tipo')},
            },
        ),
    ]
