# Generated by Django 5.1.7 on 2025-04-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_recibo_codigo_verificacao_recibo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='codigo_verificacao',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
