# Generated by Django 5.1.7 on 2025-03-31 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('carga_horaria', models.PositiveIntegerField(help_text='Carga horária em horas')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='escola.instituicao')),
            ],
            options={
                'unique_together': {('nome', 'instituicao')},
            },
        ),
    ]
