# Generated by Django 5.1.7 on 2025-04-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_disciplina_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professores',
        ),
    ]
