# Generated by Django 5.1.7 on 2025-04-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0002_instituicao_inicio_teste_instituicao_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aluno', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20)),
                ('nacionalidade', models.CharField(blank=True, max_length=100)),
                ('naturalidade', models.CharField(blank=True, max_length=100)),
                ('documento_identidade', models.CharField(blank=True, max_length=50)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('data_emissao_documento', models.DateField(blank=True, null=True)),
                ('local_emissao_documento', models.CharField(blank=True, max_length=100)),
                ('endereco_completo', models.TextField(blank=True)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('tem_alguma_deficiencia', models.BooleanField(default=False)),
                ('descricao_deficiencia', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('plano_saude', models.CharField(blank=True, max_length=100)),
                ('situacao_escolar_anterior', models.CharField(blank=True, max_length=255)),
                ('escola_anterior', models.CharField(blank=True, max_length=255)),
                ('ano_concluido_anterior', models.CharField(blank=True, max_length=10)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/')),
                ('pai_nome', models.CharField(blank=True, max_length=255)),
                ('mae_nome', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='escola.instituicao')),
            ],
        ),
    ]
