# Generated by Django 5.1.7 on 2025-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/foto_perfil/'),
        ),
    ]
