# Generated by Django 5.1.7 on 2025-04-08 08:09

import aluno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=aluno.models.get_unique_filename),
        ),
    ]
