# Generated by Django 5.1.7 on 2025-04-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='numero_aluno',
        ),
    ]
