# Generated by Django 5.1.7 on 2025-04-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0003_remove_disciplina_professores'),
        ('professor', '0002_professor_ativo_professor_bairro_professor_cidade_and_more'),
        ('turma', '0005_remove_turma_professores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensinos', to='disciplina.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensinos', to='professor.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensinos', to='turma.turma')),
            ],
            options={
                'verbose_name': 'Atribuição de Ensino',
                'verbose_name_plural': 'Atribuições de Ensino',
                'unique_together': {('professor', 'disciplina', 'turma')},
            },
        ),
    ]
